services:
  nuxt_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    command: >
      sh -c "npm run build && node .output/server/index.mjs"
