version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: directus_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - directus_network

  directus:
    image: directus/directus:latest
    container_name: directus_app
    environment:
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET: ${SECRET}
      PUBLIC_URL: ${PUBLIC_URL}
    depends_on:
      - db
    ports:
      - "8055:8055"
    networks:
      - directus_network
    volumes:
      - ./uploads:/uploads
      - ./snapshot:/snapshot/snapshot

volumes:
  db_data:

networks:
  directus_network:
