name: Build, Test, and Deploy Nuxt

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./merlaart  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt project
        run: npm run build

      - name: Build Docker image
        run: docker build -t your-docker-username/merlaart:latest .

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push your-docker-username/merlaart:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull your-docker-username/merlaart:latest
            docker stop merlaart-nuxt_app-1 || true
            docker rm merlaart-nuxt_app-1 || true
            docker run -d --name merlaart-nuxt_app-1 -p 3000:3000 your-docker-username/merlaart:latest
