name: Deploy Database

on:
  workflow_run:
    workflows: ["Deploy Frontend"]
    types:
      - completed

jobs:
  deploy-database:
    runs-on: ubuntu-latest
    if: env.DEPLOY_DATABASE == 'true'

    steps:
      - name: Deploy PostgreSQL to server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop directus_db || true
            docker rm directus_db || true

            docker run -d --name directus_db \
            -e POSTGRES_USER=${{ secrets.DB_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e POSTGRES_DB=${{ secrets.DB_DATABASE }} \
            -p 5432:5432 \
            postgres:latest
