name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./merlaart  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load deployment config
        run: |
          set -a
          source deploy-config.env
          set +a

      - name: Setup Node.js
        if: ${{ env.DEPLOY_FRONTEND == 'true' }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        if: ${{ env.DEPLOY_FRONTEND == 'true' }}
        run: npm install

      - name: Build Nuxt project
        if: ${{ env.DEPLOY_FRONTEND == 'true' }}
        run: npm run build

      - name: Build Docker image
        if: ${{ env.DEPLOY_FRONTEND == 'true' }}
        run: docker build -t tailpwnz/merlaart:latest .

      - name: Login to Docker Hub
        if: ${{ env.DEPLOY_FRONTEND == 'true' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker image to Docker Hub
        if: ${{ env.DEPLOY_FRONTEND == 'true' }}
        run: docker push tailpwnz/merlaart:latest

      - name: Deploy to server via SSH
        if: ${{ env.DEPLOY_FRONTEND == 'true' }}
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull tailpwnz/merlaart:latest
            docker stop merlaart-nuxt_app-1 || true
            docker rm merlaart-nuxt_app-1 || true
            docker run -d --name merlaart-nuxt_app-1 -p 3000:3000 tailpwnz/merlaart:latest
