name: Deploy Directus

on:
  workflow_run:
    workflows: ["Deploy Database"]
    types:
      - completed

jobs:
  deploy-directus:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Directus to server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker run -d --name directus_app \
            -e DB_CLIENT=pg \
            -e DB_HOST=directus_db \
            -e DB_PORT=5432 \
            -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e SECRET=${{ secrets.SECRET }} \
            -e PUBLIC_URL=${{ secrets.PUBLIC_URL }} \
            --link directus_db \
            -p 8055:8055 \
            directus/directus:latest
